### PR TITLE
Vpc UUID clusters

### PR DESCRIPTION
**Pull request by JohnDzialo**
* Added the ability to specify VPC UUID for a database cluster
* Added an output for the VPC UUID

### CODE REVIEW

**Review by mohsenSy — CHANGES_REQUESTED** [review]
Please assign value for the private_network_uuid resource argument like this
```
private_network_uuid = var.private_network_uuid == "" ? null : var.private_network_uuid
```
So when no value is provided by the user it will use the default value of null, the value of "" is not allowed

**Comment by JohnDzialo** [comment]
OH, interesting.

OK could we do that at the variable level?  As in set the default to `null` [here](https://github.com/mohsenSy/terraform-digitalocean-db/blob/main/variables.tf#L33)

**Comment by mohsenSy** [comment]
@JohnDzialo if you do it at the variable level then terraform registry will believe that this variable is required and will show in the module's page that 7 variables are required instead of 6, so it is better to do it in the resources and not at the variable level

**Comment by JohnDzialo** [comment]
@mohsenSy Got it!   Thanks!

Updated the PR with a local variable.

**Review by mohsenSy — APPROVED** [review]

**Pull request merged**
